### PR TITLE
node 9.8.0

### PR DESCRIPTION
**Pull request by dmalan**
No rush, but mind making sure to test offline too?

### CODE REVIEW

**Comment by YoginthS** [comment]
Node 8.9.4 will be good! cuz it is **LTS**

**Comment by dmalan** [comment]
We tend to use LTS distributions but the latest version of various packages so students can use the latest for final projects, actually!

**Comment by YoginthS** [comment]
Then we can move to **9.4.0**

**Comment by dmalan** [comment]
Oh! Very true. (8.10.0 was LTS, https://nodejs.org/en/.)

**Comment by YoginthS** [comment]
**Awesome**, Thanks for Updating me @dmalan

**Comment by YoginthS** [comment]
9.8.0 is a Good choice to stay updated!

**Comment by dmalan** [comment]
Why better?

**Comment by YoginthS** [comment]
9.8.0 is the latest release still it will have some bugs to be fixed! But 9.4.0 is little old it might have big community including me to support issues and lot.

**Comment by dmalan** [comment]
That's okay, for non-mission-critical packages, we tend to offer students the very latest.

**Pull request merged**
