### PR TITLE
removes FLASK_DEBUG, adds --reload

### PR DESCRIPTION
**Pull request by dmalan**
Should only be merged after https://github.com/cs50/python-cs50/pull/33 is.

### CODE REVIEW

**Comment by dmalan** [comment]
@kzidane where is `python-cs50` installed?

**Comment by kzidane** [comment]
@dmalan https://github.com/cs50/ide50/blob/develop/update50#L146

**Comment by dmalan** [comment]
Thanks! What are the parens for here? https://github.com/cs50/ide50/blob/120b6cd3255279ea6f4242775528ce5126d74ba2/update50#L163

**Comment by dmalan** [comment]
Ready to merge, @kzidane !

**Comment by kzidane** [comment]
Don't think the parentheses are needed here. Maybe there were before and we left after simplification. Just rebased on develop. Will merge shortly after testing.

**Pull request merged**
