### PR TITLE
override user's umask with sudo

### PR DESCRIPTION
**Pull request by kzidane**
@glennholloway, any takes?

cc @dmalan

### CODE REVIEW

**Comment by dmalan** [comment]
Let me defer to @glennholloway! This is meant to resolve issues like

```
sudo pip install foo
```

whereby `foo` then gets installed in `/usr/local/lib` without being world-readable, as happens as expected with, e.g.:

```
sudo su -
pip install foo
```

**Comment by kzidane** [comment]
For reference, see https://www.sudo.ws/man/1.8.9/sudoers.man.html#SUDOERS_OPTIONS!

**Comment by glennholloway** [comment]
@kzidane: This sounds fine to me (I learn something useful here every day), but I don't understand how you get away without explicitly specifying the "more permissive umask in sudoers", in addition to setting the override flag.
cc: @dmalan

**Comment by kzidane** [comment]
@glennholloway, it defaults to `0022`? Per the same link above:

> umask
> 
> Umask to use when running the command. Negate this option or set it to 0777 to preserve the user's umask. The actual umask that is used will be the union of the user's umask and the value of the umask option, **which defaults to 0022**.

**Comment by glennholloway** [comment]
Sounds good. Ship it!

**Pull request merged**
