### PR TITLE
added reminder to close and re-open terminal windows

### PR DESCRIPTION
**Pull request by dmalan**
@glennholloway a minor change for when we next roll out an update! 

CC @kzidane

### CODE REVIEW

**Comment by kzidane** [comment]
Guess we should remove from [`postinst`](https://github.com/cs50/ide50/blob/a35784b1660e81246955bce92a7a6ffe8ee14eb8/ide50/debian/postinst#L178)? Should've added to `update50`!

**Comment by dmalan** [comment]
Oh, yes, that looks like the wrong place. Mind updating the PR?

**Comment by kzidane** [comment]
Done!

**Comment by kzidane** [comment]
@dmalan any reason not to merge this one yet?

**Comment by dmalan** [comment]
:shipit:

**Pull request merged**
